excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://augustoppimenta.github.io
title: Augusto Pimenta
email: augustoppimenta@gmail.com
author: Augusto Pimenta
description: UX Designer
meta-description: "Designer interessado no desenvolvimento de produtos e servi√ßos digitais"
paginate: 5
google_analytics:
